[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "gitpy-cli"
version = "0.1.0"
description = "Gitpy CLI"
readme = "README.md"
requires-python = ">=3.8"
dependencies = []

[project.scripts]
gitpy-cli = "gitpy:main"

[tool.setuptools]
py-modules = ["gitpy", "Gitpyfuntion"]
